# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('surname', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('publish_year', models.DateTimeField()),
                ('book_to_author', models.ManyToManyField(to='mainApp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('book_to_genre', models.ManyToManyField(to='mainApp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=128, null=True)),
                ('licens', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('book_to_publisher', models.ManyToManyField(to='mainApp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('content', models.CharField(blank=True, max_length=512, null=True)),
                ('notes', models.CharField(blank=True, max_length=512, null=True)),
                ('review_to_book', models.ManyToManyField(to='mainApp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('like', models.PositiveIntegerField()),
                ('dislike', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('nickname', models.CharField(blank=True, max_length=128, null=True)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('book_to_user', models.ManyToManyField(to='mainApp.Book')),
            ],
        ),
        migrations.AddField(
            model_name='reviewcomments',
            name='comment_to_user',
            field=models.ManyToManyField(to='mainApp.User'),
        ),
    ]
