# Generated by Django 2.0.5 on 2018-05-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_to_books',
            field=models.ManyToManyField(to='mainApp.Books'),
        ),
    ]
